fishlist:
  tuna:
    min: 70
    max: 300
    name: §bマグロ
    material: COOKED_MUTTON
    rarity: §e★★★
    comment: うまそう
    modelData: 1
  whale:
    min: 10000
    max: 100000
    name: §bクジラ
    material: RABBIT
    rarity: ☆
    comment: でかい、なんで取っているんだ...
    modelData: 1
  creeperFish:
    min: 100
    max: 200
    name: §bクリーパーFish
    material: APPLE
    rarity: §e★★★
    comment: 今にも爆破しそうだ
    modelData: 1
  Flathead:
    min: 40
    max: 90
    name: §bマゴチ
    material: cod
    rarity: §e★★★★
    comment: 高級食材、頭の棘に注意
  Caranginae:
    min: 10
    max: 160
    name: §bアジ
    material: cod
    rarity: §e★
    comment:
  sardine:
    min: 10
    max: 30
    name: §bイワシ
    material: cod
    rarity: §e★
    comment: DHAが豊富
  Carassius_auratus:
    min: 5
    max: 30
    name: §bキンギョ
    material: cod
    rarity: §e★★
    comment: あまり美味しくない
  Anguilla:
    min: 10
    max: 40
    name: §bウナギ
    material: cod
    rarity: §e★★★
    comment:
  Parahucho_perry:
    min: 30
    max: 70
    name: §bイトウ
    material: cod
    rarity: §e★★★★★
    comment: 絶滅危惧種
  Snow_crab:
    min: 50
    max: 70
    name: §bズワイガニ
    material: cod
    rarity: §e★★★
    comment:

