fishlist:
  tuna:
    min: 70
    max: 300
    name: §bマグロ
    material: COOKED_MUTTON
    rarity: §e★★★
    comment: うまそう
  whale:
    min: 10000
    max: 100000
    name: §bクジラ
    material: RABBIT
    rarity: ☆
    comment: でかい、なんで取っているんだ...
  creeperFish:
    min: 100
    max: 200
    name: §bクリーパーFish
    material: APPLE
    rarity: §e★★★
    comment: 今にも爆破しそうだ